# Generated by Django 4.1 on 2023-11-10 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfor',
            fields=[
                ('idCustomer', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameCustomer', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Na', 'Nam'), ('Nu', 'Nữ'), ('Kh', 'Khác')], max_length=100)),
                ('identityCard', models.CharField(max_length=12)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'CustomerInfo',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('idFloor', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameFloor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Floor',
            },
        ),
        migrations.CreateModel(
            name='RoomKind',
            fields=[
                ('idKind', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameKind', models.CharField(choices=[('STD-S', 'Standard - Singer bed'), ('STD-D', 'Standard - Double bed'), ('SUP-S', 'Superior - Single bed'), ('SUP-D', 'Superior - Double bed')], max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('descript', models.TextField()),
            ],
            options={
                'db_table': 'RoomKind',
            },
        ),
        migrations.CreateModel(
            name='RoomPicture',
            fields=[
                ('idPicture', models.BigAutoField(primary_key=True, serialize=False)),
                ('linkPicture', models.CharField(max_length=100)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.roomkind')),
            ],
            options={
                'db_table': 'RoomPicture',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idRoom', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameRoom', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OK', 'Phòng sẵn sàng'), ('ER', 'Phòng hỏng')], default='OK', max_length=100)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.floor')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.roomkind')),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('idRequest', models.BigAutoField(primary_key=True, serialize=False)),
                ('dateCheckin', models.DateTimeField()),
                ('dateCheckout', models.DateTimeField()),
                ('numberOfRoom', models.IntegerField()),
                ('numberOfChildren', models.IntegerField()),
                ('numberOfAdults', models.IntegerField()),
                ('status', models.CharField(choices=[('CD', 'Chờ duyệt'), ('HL', 'Hợp lệ'), ('KHL', 'Không hợp lệ')], default='CD', max_length=100)),
                ('note', models.TextField(default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customerinfor')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.roomkind')),
            ],
            options={
                'db_table': 'CustomerRequest',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('idBooking', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DN', 'Đã nhận phòng'), ('DH', 'Đã hủy'), ('CN', 'Chờ nhận phòng')], default='CN', max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('customerRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.customerrequest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.room')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
